### PR TITLE
possibility to override ScopePaths

### PR DESCRIPTION
**Pull request by vincent-fuchs**
implementing https://github.com/societe-generale/arch-unit-gradle-plugin/issues/19

+ upgrading arch-unit-build-plugin-core and its required adaptations

### CODE REVIEW

**Comment by mpetitdant** [comment]
Hello Vincent, is this PR still in your plans ?

**Comment by vincent-fuchs** [comment]
hi @mpetitdant , I had totally forgotten this one, sorry.

too many changes in master since I started this PR - I've tried a simpler approach in https://github.com/societe-generale/arch-unit-gradle-plugin/pull/32, you can build and try it there. I will try to test it on my side in coming days

**Comment by vincent-fuchs** [comment]
replaced by https://github.com/societe-generale/arch-unit-gradle-plugin/pull/32

**Comment by vincent-fuchs** [comment]
@mpetitdant , see https://github.com/societe-generale/arch-unit-gradle-plugin/issues/19#issuecomment-1500903307 . If you give positive feedback, I can probably give a release in next few weeks

**Pull request closed without merging**
